"""poddaje sie

Revision ID: 73acf1b74bfb
Revises: 96f8646fa5b5
Create Date: 2023-03-06 03:17:25.579370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73acf1b74bfb'
down_revision = '96f8646fa5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('registration')
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', mysql.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('registration', mysql.TIMESTAMP(), nullable=True))

    # ### end Alembic commands ###
