"""User personalities types

Revision ID: f3090317e345
Revises: a51b48d8c311
Create Date: 2023-03-06 10:34:37.805299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3090317e345'
down_revision = 'a51b48d8c311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personality_type_one', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('personality_type_two', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('personality_type_two')
        batch_op.drop_column('personality_type_one')

    # ### end Alembic commands ###
