"""full users table

Revision ID: fed82238cdea
Revises: f3a6190ddb15
Create Date: 2023-03-05 18:12:16.484280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed82238cdea'
down_revision = 'f3a6190ddb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dark_theme', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('friends', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('registration', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('pet_preference', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_interests', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('user_interests')
        batch_op.drop_column('pet_preference')
        batch_op.drop_column('last_login')
        batch_op.drop_column('registration')
        batch_op.drop_column('friends')
        batch_op.drop_column('dark_theme')
        batch_op.drop_column('avatar')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
