"""users fix

Revision ID: 46dcc563ce87
Revises: b8d14bb96d1b
Create Date: 2023-03-05 22:18:19.446664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46dcc563ce87'
down_revision = 'b8d14bb96d1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_ibfk_1', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_foreign_key('messages_ibfk_1', 'user', ['reciever_id'], ['id'])

    # ### end Alembic commands ###
