"""User personalities types

Revision ID: a51b48d8c311
Revises: 59bdc804b89e
Create Date: 2023-03-06 10:27:27.456535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a51b48d8c311'
down_revision = '59bdc804b89e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('personality_type_two')
        batch_op.drop_column('personality_type_one')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('personality_type_one', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('personality_type_two', mysql.TEXT(), nullable=True))

    # ### end Alembic commands ###
