"""Question for conversation fix

Revision ID: c1f3cda2d45c
Revises: 5beea2b638d3
Create Date: 2023-03-06 07:25:22.979651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1f3cda2d45c'
down_revision = '5beea2b638d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_for_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.Text(), nullable=True))
        batch_op.drop_constraint('question_for_conversation_ibfk_1', type_='foreignkey')
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_for_conversation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('question_for_conversation_ibfk_1', 'questions', ['question_id'], ['id'])
        batch_op.drop_column('question')

    # ### end Alembic commands ###
