"""users second fix

Revision ID: c81b402f2e3e
Revises: 46dcc563ce87
Create Date: 2023-03-05 22:20:21.576947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81b402f2e3e'
down_revision = '46dcc563ce87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_constraint('match_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_foreign_key('match_ibfk_2', 'user', ['second_user'], ['id'])

    # ### end Alembic commands ###
