interests = [
    "Sport",
    "Sporty drużynowe",
    "Sporty ekstremalne",
    "Filmy",
    "Gry komputerowe",
    "Gry planszowe",
    "Historia",
    "Motoryzacja",
    "Podróżowanie",
    "Moda",
    "Fotografia",
    "Literatura",
    "Muzyka",
    "Gotowanie",
    "Taniec",
    "Informatyka",
    "Geografia",
    "Biologia",
    "Fizyka",
    "Chemia",
    "Architektura",
    "Aktorstwo",
    "Polityka",
    "Malarstwo",
    "Nauka języków"
]